### ISSUE TITLE
Flutter: Android license status unknown

### ISSUE THREAD

**Issue by J4NV5** [tadfisher/android-nixpkgs#18]
It appears the use of this library with flutter does successfully include Android SDK, but `flutter doctor` says `✗ Android license status unknown.`, and of course running `flutter doctor --android-licenses` produces an error: 
```
Error: Could not determine SDK root.
Error: Either specify it explicitly with --sdk_root= or move this package into its expected location: <sdk>/cmdline-tools/latest/
```
How are the licenses handled? I knew with previous iterations of using the android SDK with flutter, the license was a read-only nix path, and could not easily be accepted deterministically.  How do you accomplish this with this library?

Thank you

**Comment by tadfisher** [comment]
How are you using this with your project?

A working Android SDK needs to use the `sdk` function (or `pkgs.androidSdk` if using the overlay). That creates what the Android SDK tools expect to see, including a `$out/licenses/` directory which contains the accepted hashes of license files.

If you are using the function, then go ahead and pass `--sdk_root=${sdk}/share/android-sdk` as `flutter doctor` asks and let me know if that works.

**Comment by J4NV5** [comment]
thanks for the quick reply!
this is how I arrived at the current state:
```
nix flake init -t github:tadfisher/android-nixpkgs
```
Then from `devshell.nix` I changed `mkDevShell` -> to `pkgs.devshell.mkShell` and the `env` to a list of submodules https://github.com/tadfisher/android-nixpkgs/blob/e470bf8067fc112f295c1780a91b7c7d7b5dc1bf/template/devshell.nix#L13-L17.

Apparently those needed to be updated.

Then I just added flutter to the mkShell packages, then ran:

```
nix develop
flutter doctor
```

**Comment by J4NV5** [comment]
(I did a PR for the above changes)
https://github.com/tadfisher/android-nixpkgs/pull/21

**Comment by J4NV5** [comment]
`$ sdkmanager --licenses`
```
Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
4 of 6 SDK package licenses not accepted. 100% Computing updates...             
Review licenses that have not been accepted (y/N)? 
```
So maybe missing 2 of the licenses?

**Comment by tadfisher** [comment]
So:

- There are 6 total android SDK licenses available for accepting.
- android-nixpkgs.sdk copies the license hashes only for the packages you install.
- The default setup from the template only requires `android-sdk-license` and `android-sdk-preview-license` to be approved
- `sdkmanager --licenses` displays all possible licenses you can accept, not only the ones that need accepting for the SDK packages you have installed.
- Thus `sdkmanager --licenses` is not the ideal way to check if the SDK is working or not.
- However, to support `flutter doctor` I can add all possible license hashes to the sdk output.

Let me see if this is feasible without bloating the closure size of a basic SDK.

**Comment by tadfisher** [comment]
`sdkmanager --licenses` should pass now.
