### ISSUE TITLE
Broken with nixpkgs >= 2022-09-24, rename `alsaLib` to `alsa-lib`

### ISSUE THREAD

**Issue by lokegustafsson** [tadfisher/android-nixpkgs#44]
This flake is broken on nixpkgs more recent than 2022-09-24
```
error: 'alsaLib' has been renamed to/replaced by 'alsa-lib'
```
See
https://github.com/NixOS/nixpkgs/commit/d06207386df9a53fe01f8a30130dfc9a839fc8fc

The fix should just be to rename `alsaLib` to `alsa-lib` in pkgs/android/emulator.nix

**Comment by tadfisher** [comment]
Fixed by #45
