### ISSUE TITLE
AAPT2 daemon startup failed

### ISSUE THREAD

**Issue by eekrain** [tadfisher/android-nixpkgs#46]
I create clean react native app and then init the flake setup with nix flake init -t github:tadfisher/android-nixpkgs.
When im trying to run yarn react-native run-android the error says

> * What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-1.4.1.aar (androidx.appcompat:appcompat:1.4.1) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /home/eekrain/.gradle/caches/transforms-3/1b40e4574e76bff5831ef4bf4270480d/transformed/appcompat-1.4.1.
         > AAPT2 aapt2-7.2.1-7984345-linux Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /home/eekrain/.gradle/caches/transforms-3/63a3df243d2d102452600006144a86df/transformed/core-1.7.0.
         > AAPT2 aapt2-7.2.1-7984345-linux Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /home/eekrain/.gradle/caches/transforms-3/63a3df243d2d102452600006144a86df/transformed/core-1.7.0.
         > AAPT2 aapt2-7.2.1-7984345-linux Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /home/eekrain/.gradle/caches/transforms-3/63a3df243d2d102452600006144a86df/transformed/core-1.7.0.
         > AAPT2 aapt2-7.2.1-7984345-linux Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /home/eekrain/.gradle/caches/transforms-3/63a3df243d2d102452600006144a86df/transformed/core-1.7.0.
         > AAPT2 aapt2-7.2.1-7984345-linux Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /home/eekrain/.gradle/caches/transforms-3/63a3df243d2d102452600006144a86df/transformed/core-1.7.0.
         > AAPT2 aapt2-7.2.1-7984345-linux Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /home/eekrain/.gradle/caches/transforms-3/63a3df243d2d102452600006144a86df/transformed/core-1.7.0.
         > AAPT2 aapt2-7.2.1-7984345-linux Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /home/eekrain/.gradle/caches/transforms-3/63a3df243d2d102452600006144a86df/transformed/core-1.7.0.
         > AAPT2 aapt2-7.2.1-7984345-linux Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.

Can i use it with react native? Im really hopeless, dont have any idea to make an android environment in nixos.

**Comment by eekrain** [comment]
Turns out i just need to override aapt2 from maven according to exact react native build tools version.

`{
    name = "GRADLE_OPTS";
    value = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${android-sdk}/share/android-sdk/build-tools/31.0.0/aapt2";
}`

**Comment by louwers** [comment]
Do you know how to get `31.0.0` from `android-sdk`?

**Comment by kjeremy** [comment]
I just ran into this too. It doesn't happen locally but if I run my gradle wrapper from a shell script on my CI machine I have to override `aapt2`.

**Comment by igor-ramazanov** [comment]
Weird, `gradle` doesn't respect the `GRADLE_OPTS` environment variable for me. I've ensured killing the daemon processes.
