### ISSUE TITLE
Missing libcryptx-legacy

### ISSUE THREAD

**Issue by lamarios** [tadfisher/android-nixpkgs#59]
I tried to run the following nix file from the readme
```
{ pkgs ? import <nixpkgs> { } }:

with pkgs;

let
  android-nixpkgs = callPackage <android-nixpkgs> {
    # Default; can also choose "beta", "preview", or "canary".
    channel = "stable";
  };

in
android-nixpkgs.sdk (sdkPkgs: with sdkPkgs; [
  cmdline-tools-latest
  build-tools-32-0-0
  platform-tools
  platforms-android-31
  emulator
])

```
then
```
nix-shell sdk.nix
```

but I get the error:
```
error: assertion '((stdenv).isLinux -> (libxcrypt-legacy != null))' failed

       at /nix/store/9slbnzb9kbrval7xj72l7mbwqmrlgz69-android-nixpkgs/android-nixpkgs/pkgs/android/ndk.nix:17:1:

           16| assert stdenv.isLinux -> autoPatchelfHook != null;
           17| assert stdenv.isLinux -> libxcrypt-legacy != null;
             | ^
           18| assert stdenv.isLinux -> ncurses5 != null;
(use '--show-trace' to show detailed location information)

```

I tried to install the libxcrypt package but that did not help

**Comment by katyo** [comment]
@lamarios It seems the problem in that fact that #57 was applied to `stable` branch. But currently `libxcrypt-legacy` package exists only for `unstable` nixos channel.

**Comment by dpc** [comment]
Everything works fine with more recent `nixos-22.11`. If you're stuck on the old one, you can use fork (see link above).

**Comment by tadfisher** [comment]
`stable` refers to the Android SDK channel, not the nixpkgs branch. We target `nixos-unstable`; if there are problems, we have near-daily tags you can pin to until you update nixpkgs.
