### ISSUE TITLE
The flake does not work on Apple Sillicon (aarch64-apple-darwin)

### ISSUE THREAD

**Issue by Teebor-Choka** [tadfisher/android-nixpkgs#63]
## What
The flake does not work, when following the readme, I followed the steps manually

## Info
Used nix pkgs version: `nix (Nix) 2.15.1`

## Problem
After entering the commands specified in the readme:
```shell
nix flake init -t github:tadfisher/android-nixpkgs
nix develop
```

The `nix develop` command fails with:
```
➜   nix develop
warning: Git tree '/Users/tester/dev/flutter-nix-hello-world' is dirty
warning: creating lock file '/Users/tester/dev/flutter-nix-hello-world/flake.lock'
warning: Git tree '/Users/tester/dev/flutter-nix-hello-world' is dirty
error: flake 'git+file:///Users/tester/dev/flutter-nix-hello-world' does not provide attribute 'devShells.aarch64-darwin.default', 'devShell.aarch64-darwin', 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'
       Did you mean devShell?
```

## Investigation
By extending the line in flake.nix as:
`flake-utils.lib.eachSystem [ "x86_64-linux" ] (system:` -> `flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-darwin" ] (system:` I get an error message:

```
error: Package ‘android-studio-stable-2022.2.1.20’ in /nix/store/6ysp0jddm896d8nn1pvj5pdaj72yra7i-source/pkgs/applications/editors/android-studio/common.nix:207 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "x86_64-linux"
         ]
```

**Comment by tadfisher** [comment]
We don't package `androidStudioPackages` (that's in nixpkgs), but thanks for the heads-up. I'll just comment out that line if it makes the flake work out-of-the-box on aarch64-darwin.
