### ISSUE TITLE
NixOS cannot start dynamically linked executable: `emulator` command

### ISSUE THREAD

**Issue by HPRIOR** [tadfisher/android-nixpkgs#99]
When using the flake provided by `nix flake init -t github:tadfisher/android-nixpkgs` on nixOS, I cannot use the emulator command (`/nix/store/86myy4i3igzb3g2s3ld154y9rfqgb7qp-android-project-dir/bin/emulator`). I am getting the error:

```text
Could not start dynamically linked executable: /nix/store/86myy4i3igzb3g2s3ld154y9rfqgb7qp-android-project-dir/bin/emulator
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

Is this expected behaviour? How else should I start an emulator?

**Comment by HPRIOR** [comment]
Attempting to debug this, but new to nix.

I noticed that when I ran `ldd` on `/nix/store/98w9jh9s6phm3pg3m0jv1zs8gdpx8gzb-emulator-35.1.2/.emulator-wrapped`, `libX11.so.6` was not found. I updated my `devshell.nix` to:

**Comment by HPRIOR** [comment]
`nix-store -q --references /nix/store/5lr5n3qa4day8l1ivbwlcby2nknczqkq-bash-5.2p26` shows:

```text
/nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44
/nix/store/5lr5n3qa4day8l1ivbwlcby2nknczqkq-bash-5.2p26
```

I have tried using an overlay to pin the version of glibc to 2.38-44, but the error persists:

```nix
{
  pkgs,
  lib,
}:
with pkgs;
# Configure your development environment.
#
# Documentation: https://github.com/numtide/devshell
  devshell.mkShell rec {
    name = "android-project";
    motd = ''
      Entered the Android app development environment.
    '';
    env = [
      {
        name = "ANDROID_HOME";
        value = "${android-sdk}/share/android-sdk";
      }
      {
        name = "ANDROID_SDK_ROOT";
        value = "${android-sdk}/share/android-sdk";
      }
      {
        name = "JAVA_HOME";
        value = jdk.home;
      }
      {
        name = "LD_LIBRARY_PATH";
        value = "$LD_LIBRARY_PATH:${builtins.toString (lib.makeLibraryPath packages)}";
      }
    ];
    packages =
      [
        nodejs_20
        android-sdk
        gradle
        jdk
      ]
      ++ lib.optionals (system == "x86_64-linux") [
        android-studio
        xorg.libX11
        (pkgs.glibc.overrideAttrs (oldAttrs: rec {
          version = "2.38-44";
        }))
      ];
  }

```

**Comment by HPRIOR** [comment]
I don't think I have the required knowledge of linux/nixos to debug this further. Any help would be much appreciated!

**Comment by HPRIOR** [comment]
Thank you. The emulator command is working now

**Comment by almantare** [comment]
> Thank you. The emulator command is working now

bro, can u help me to find /nix/store/apab5i73dqa09wx0q27b6fbhd1r18ihl-glibc-2.39-31/lib/ld-linux-x86-64.so.2?

**Comment by RatCornu** [comment]
Hello I have the same problem with every other command in `/nix/store/...-android-sdk-env/share/android-sdk/build-tools/` like `aapt2`, `apksigner`, `zipalign`, ... Is there a fix for this too?
